wildfly/wildfly-tck-runners

.gitignore
concurrency/README.md
concurrency/logging.properties
concurrency/pom.xml
concurrency/src/assembly/assembly-server-tck-lib.xml
concurrency/src/main/resources/configure-server.cli
concurrency/src/test/resources/arquillian.xml
concurrency/suite.xml

Issue: https://issues.redhat.com/browse/WFLY-16237

[WFLY-16237] adds initial concurrency tck runner

---

jakarta-xml-binding/Dockerfile
jakarta-xml-binding/README.adoc
jakarta-xml-binding/bin/javaenv.sh
jakarta-xml-binding/bin/run-tck.sh
jakarta-xml-binding/build.sh
jakarta-xml-binding/jboss-bashrc
jakarta-xml-binding/start.sh

https://issues.redhat.com/browse/WFLY-16455

[WFLY-16455] Add a TCK runner for the Jakarta XML Binding TCK.

---

concurrency/concurrency-tck-runner/src/main/resources/configure-server.cli

Set the EJB and Undertow security domain.

---

authentication/wildfly-mods/profile.xml

Allow the Authentication TCK to run with Java 17.

---

authentication/wildfly-mods/profile.xml
authentication/wildfly/pom.xml
security/.gitignore
security/clean-tck.sh
security/run-tck.sh
security/wildfly-mods/arquillian.xml
security/wildfly-mods/build_xml.patch
security/wildfly-mods/profile.xml
security/wildfly-mods/transform.xslt
security/wildfly/configure-server.cli
security/wildfly/pom.xml

This does not complete issue#27 but gets the runner in place so we can activate it and start to get some results in CI.

Issue #27 Add security TCK runner

---

.github/workflows/concurrency-tck.yml

Allow the concurrency TCK to be manually ran.

---

.github/workflows/security-tck.yml

Add a CI job for the security TCK.

---

concurrency/concurrency-tck-setup/pom.xml
concurrency/pom.xml

[Issue 43] Move to concurrency-tck 3.0.2

---

.github/workflows/authentication-tck.yml
.github/workflows/concurrency-tck.yml
.github/workflows/security-tck.yml

[Issue_70] Update to actions/checkout@v3

---

authentication/wildfly-mods/profile.xml
authentication/wildfly/pom.xml
concurrency/concurrency-tck-runner/pom.xml
concurrency/pom.xml
faces/wildfly/pom.xml
jakarta-xml-binding/README.adoc
security/wildfly-mods/profile.xml
security/wildfly/pom.xml
wf-core-tck-runner/pom.xml

While doing this I updated various other dependencies to match what was used in 27.0.1.
Fixed various things I encountered when building the changed modules, particularly the need to configure JBoss Nexus as a repository.
Resolves #74

[Issue 74] Update to WildFly 27.0.1.Final

---

faces/bin/run-tck.sh

Add flags to select WF profiles

---

wf-core-tck-runner/pom.xml

[99] Upgrade the Jakarta REST TCK to 3.1.4.

---

authentication/wildfly-mods/profile.xml
authentication/wildfly/pom.xml
concurrency/concurrency-tck-runner/pom.xml
faces/wildfly/pom.xml
security/wildfly-mods/profile.xml
security/wildfly/pom.xml
wf-core-tck-runner/pom.xml

[104] Upgrade tests to default to using WildFly 30.0.0.Final.

---

jakarta-xml-binding/bin/run-tck.sh

Upgrade to the XML Binding TCK 4.0.1

upgrade to XML Binding TCK version 4.0.1

---

concurrency/concurrency-tck-setup/pom.xml
concurrency/pom.xml

[144] Upgrade the Jakarta Concurrency TCK to 3.0.3.

---

.github/workflows/concurrency-tck.yml
concurrency/concurrency-tck-runner/pom.xml
concurrency/concurrency-tck-setup/pom.xml
concurrency/pom.xml

Upgrade the Jakarta Concurrency TCK to 3.0.4.

---

security/clean-tck.sh
security/run-tck.sh
security/wildfly-mods/arquillian.xml
security/wildfly-mods/profile.xml
security/wildfly/configure-server.cli
security/wildfly/pom.xml

Initial commit for upgrading the Jakarta Security TCK.

---

faces/bin/run-tck.sh
faces/wildfly-mods/global-excludes-profile.xml
faces/wildfly-mods/newtck-exclusions.txt
faces/wildfly-mods/se21-excludes-profile.xml
faces/wildfly-mods/se21-newtck-exclusions.txt
faces/wildfly-mods/transform.xslt

Resolves #166 against the 33.x branch
Upstream: #168

[Issue_166] Add the ability to exclude Faces new TCK tests; exclude challenge #1935 tests

---

authentication/wildfly-mods/profile.xml
authentication/wildfly/pom.xml
concurrency/concurrency-tck-runner/pom.xml
core-profile/pom.xml
faces/wildfly/pom.xml

Port https://github.com/wildfly/wildfly-tck-runners/commit/25eb71669b5f44cbe808860e5cd0be935c6e81c9 from the 33.x branch

Move to WildFly 33 Beta1 and current plugin versions

---

.github/dependabot.yml
.github/workflows/servlet-tck.yml
servlet-tck/README.adoc
servlet-tck/pom.xml
servlet-tck/tck-runner/pom.xml
servlet-tck/tck-runner/src/test/java/org/wildfly/tck/servlet/arquillian/WildFlyArquillianExtension.java
servlet-tck/tck-runner/src/test/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
servlet-tck/tck-runner/src/test/resources/arquillian.xml
servlet-tck/tck-runner/src/test/resources/configure-server.cli
servlet-tck/tck-runner/src/test/resources/logging.properties
servlet-tck/tck-setup/pom.xml

[194] Create a TCK runner for the Jakarta Servlet TCK.

---

authentication/clean-tck.sh
authentication/run-tck.sh

https://github.com/wildfly/wildfly-tck-runners/issues/225

wildfly-tck-runners/issues/225 Investigate if glassfish-7.0.0.zip can be removed from authentication/faces/security TCK runners
